[server]
headless = true
enableCORS = true
enableXsrfProtection = false
port = 8501

[theme]
primaryColor = "#FFB6C1"  # Light Pink
backgroundColor = "#FFF8DC"  # Cornsilk
secondaryBackgroundColor = "#E6E6FA"  # Lavender
textColor = "#5D4037"  # Brown
font = "sans serif"