[server]
headless = true
enableCORS = true
enableXsrfProtection = false
port = 8501

[theme]
primaryColor = "#8B4513"
backgroundColor = "#F5DEB3"
secondaryBackgroundColor = "#D2B48C"
textColor = "#000000"
font = "serif"